#!/bin/bash

PAIR_FILE=~/.dotfiles/scripts/pair/pair.cfg
if [ ! -f $PAIR_FILE ]; then echo "ERRO: Arquivo 'pair.cfg' nao encontrado. Configuracoes nao alteradas." && exit 1; fi
. $PAIR_FILE
if [ ! "$1" ]; then echo 'Argumento obrigatorio: com quem voce esta pareando?' && exit 1; fi
git config --global user.name "$1 & $MY_NAME_IS"
echo "Agora pareando com '$1'"
echo "Comitando como '`git config --get user.name`'"
