#!/bin/bash

PAIR_FILE=~/.dotfiles/scripts/pair/pair.cfg
if [ ! -f $PAIR_FILE ]; then echo "ERRO: Arquivo 'pair.cfg' nao encontrado. Configuracoes nao alteradas." && exit 1; fi
. $PAIR_FILE
git config --global user.name "$MY_NAME_IS"
echo "Nao pareando com mais ninguem"
echo "Nome na configuracao do git restaurado para '$MY_NAME_IS'"
